#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    if ! [ -d /usr/share/one/gems/ ]; then
        cat <<EOF
==========================[ WARNING ]==================================
Packaged Ruby gems not symlinked to /usr/share/one/gems/. Don't forget
to manually execute command /usr/share/one/install_gems to install or
update all the OpenNebula required Ruby gems system-wide !!!
==========================[ WARNING ]==================================
EOF
    fi
fi

#DEBHELPER#
