.TH ECONE-SERVER "1" "August 2010" "econe-server" "User Commands"
.SH NAME
econe-server \- OpenNebula EC2 Query service
.SH SYNOPSIS
econe\-server <COMMAND>
.SH DESCRIPTION
.B econe\-server
start or stop OpenNebula EC2 Query service
.SH COMMANDS
.PP
start
.IP
start the EC2 Query service
.PP
stop
.IP
stop the EC2 Query service
.SH FILES
.I /etc/econe.conf
.RS
The EC2 Query service configuration file.
.RE
.I /var/log/one/econe-server.log
.RS
The econe server log file.
.SH COPYRIGHT
OpenNebula is Copyright 2002\-2010, Distributed Systems Architecture Group, Universidad
Complutense de Madrid (dsa\-research.org)
.SH AUTHOR
This manual page was written by Damien Raude-Morvan <drazzib@debian.org>,
for the Debian GNU/Linux system (but may be used by others).