.TH MM_SCHED "1" "August 2010" "mm_sched" "User Commands"
.SH NAME
mm_sched \- OpenNebula scheduler process
.SH SYNOPSIS
mm_sched
.SH DESCRIPTION
.B mm_sched
is OpenNebula scheduler process, in charge of the VM to cluster node matching.
.B mm_sched
is started by
.BR one (1)
startup script
.SH FILES
.I /var/log/one/sched.log
.RS
The scheduler log file.
.SH COPYRIGHT
OpenNebula is Copyright 2002\-2010, Distributed Systems Architecture Group, Universidad
Complutense de Madrid (dsa\-research.org)
.SH AUTHOR
This manual page was written by Damien Raude-Morvan <drazzib@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.SH "SEE ALSO"
.BR one (1),
.BR oned (1)
