.TH ONE "1" "August 2010" "one" "User Commands"
.SH NAME
one \- OpenNebula startup script
.SH SYNOPSIS
one <COMMAND>
.SH DESCRIPTION
.B one
start or stop OpenNebula core and scheduler
.SH COMMANDS
.PP
start
.IP
start the oned and mm_sched services
.PP
stop
.IP
stop the oned and mm_sched services
.SH COPYRIGHT
OpenNebula is Copyright 2002\-2010, Distributed Systems Architecture Group, Universidad
Complutense de Madrid (dsa\-research.org)
.SH AUTHOR
This manual page was written by Damien Raude-Morvan <drazzib@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.SH "SEE ALSO"
.BR oned (1),
.BR mm_sched (1)
