.TH ONED "1" "August 2010" "oned" "User Commands"
.SH NAME
oned \- OpenNebula core process
.SH SYNOPSIS
oned
.SH DESCRIPTION
.B oned
is OpenNebula core process, attends the CLI requests, manages the pools and all the components.
.B oned
is started by
.BR one (1)
startup script
.SH FILES
.I /etc/oned.conf
.RS
The main OpenNebula configuration file.
.RE
.I /var/log/one/oned.log
.RS
The core OpenNebula log file.
.SH COPYRIGHT
OpenNebula is Copyright 2002\-2010, Distributed Systems Architecture Group, Universidad
Complutense de Madrid (dsa\-research.org)
.SH AUTHOR
This manual page was written by Damien Raude-Morvan <drazzib@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.SH "SEE ALSO"
.BR one (1),
.BR mm_sched (1)
