#!/bin/sh

set -e

ONEHOME=/var/lib/one
ONEAUTH=$ONEHOME/.one/one_auth
ONE_GROUP=oneadmin
ONE_USER=oneadmin

if [ "$1" = "configure" ]; then
    chgrp "${ONE_GROUP}" /etc/one
    chmod 0751 /etc/one

    # Fix permissions root:oneadmin (0640/0750) recursively
    for F in /etc/one/fireedge-server.conf;
    do
        chgrp -R "${ONE_GROUP}" "${F}" || true
        find "${F}" -type d -exec chmod 0750 {} \; || true
        find "${F}" -type f -exec chmod 0640 {} \; || true
    done
fi
