# Common to Sunstone, OCCI and ECONE

dist/usr/lib/one/ruby/OpenNebulaVNC.rb                  /usr/lib/one/ruby/
dist/usr/lib/one/ruby/opennebula_guac.rb                /usr/lib/one/ruby/
dist/usr/lib/one/ruby/OpenNebulaAddons.rb               /usr/lib/one/ruby/
dist/usr/lib/one/ruby/opennebula_vmrc.rb                /usr/lib/one/ruby/

dist/usr/bin/novnc-server /usr/bin/

# Sunstone

dist/usr/lib/one/sunstone/config.ru /usr/lib/one/sunstone/

dist/etc/one/sunstone-server.conf  /etc/one/
dist/etc/one/sunstone-logos.yaml  /etc/one/

dist/etc/one/sunstone-views.yaml   /etc/one/
dist/etc/one/sunstone-views/*      /etc/one/sunstone-views/

dist/usr/lib/one/sunstone/*.rb                      /usr/lib/one/sunstone/
dist/usr/lib/one/sunstone/models/Sunstone*          /usr/lib/one/sunstone/models/
dist/usr/lib/one/sunstone/models/sunstone_*         /usr/lib/one/sunstone/models/
dist/usr/lib/one/sunstone/public/*                  /usr/lib/one/sunstone/public/
dist/usr/lib/one/sunstone/views/*                   /usr/lib/one/sunstone/views/

dist/usr/lib/one/sunstone/routes/* /usr/lib/one/sunstone/routes/

dist/usr/bin/sunstone-server    /usr/bin/

dist/usr/share/one/websockify/* /usr/share/one/websockify/

### See https://github.com/OpenNebula/packages/issues/54
#dist/var/lib/one/sunstone/main.js /var/lib/one/sunstone/

# ECONE

dist/etc/one/econe.conf          /etc/one/

dist/etc/one/ec2query_templates/*  /etc/one/ec2query_templates/

dist/usr/bin/econe-server  /usr/bin/

dist/usr/lib/one/ruby/cloud/econe/econe-server.rb         /usr/lib/one/ruby/cloud/econe/
dist/usr/lib/one/ruby/cloud/econe/econe_application.rb    /usr/lib/one/ruby/cloud/econe/
dist/usr/lib/one/ruby/cloud/econe/elastic_ip.rb           /usr/lib/one/ruby/cloud/econe/
dist/usr/lib/one/ruby/cloud/econe/ImageEC2.rb             /usr/lib/one/ruby/cloud/econe/
dist/usr/lib/one/ruby/cloud/econe/EC2QueryServer.rb       /usr/lib/one/ruby/cloud/econe/
dist/usr/lib/one/ruby/cloud/econe/ebs.rb                  /usr/lib/one/ruby/cloud/econe/
dist/usr/lib/one/ruby/cloud/econe/instance.rb             /usr/lib/one/ruby/cloud/econe/
dist/usr/lib/one/ruby/cloud/econe/keypair.rb              /usr/lib/one/ruby/cloud/econe/
dist/usr/lib/one/ruby/cloud/econe/net_ssh_replacement.rb  /usr/lib/one/ruby/cloud/econe/
dist/usr/lib/one/ruby/cloud/econe/tags.rb                 /usr/lib/one/ruby/cloud/econe/
dist/usr/lib/one/ruby/cloud/econe/views/*                 /usr/lib/one/ruby/cloud/econe/views/

dist/usr/bin/econe-allocate-address      /usr/bin/
dist/usr/bin/econe-associate-address     /usr/bin/
dist/usr/bin/econe-describe-addresses    /usr/bin/
dist/usr/bin/econe-describe-images       /usr/bin/
dist/usr/bin/econe-describe-instances    /usr/bin/
dist/usr/bin/econe-disassociate-address  /usr/bin/
dist/usr/bin/econe-register              /usr/bin/
dist/usr/bin/econe-release-address       /usr/bin/
dist/usr/bin/econe-run-instances         /usr/bin/
dist/usr/bin/econe-terminate-instances   /usr/bin/
dist/usr/bin/econe-upload                /usr/bin/
dist/usr/bin/econe-attach-volume         /usr/bin/
dist/usr/bin/econe-create-volume         /usr/bin/
dist/usr/bin/econe-delete-volume         /usr/bin/
dist/usr/bin/econe-describe-volumes      /usr/bin/
dist/usr/bin/econe-detach-volume         /usr/bin/
dist/usr/bin/econe-reboot-instances      /usr/bin/
dist/usr/bin/econe-start-instances       /usr/bin/
dist/usr/bin/econe-stop-instances        /usr/bin/
dist/usr/bin/econe-create-keypair        /usr/bin/
dist/usr/bin/econe-delete-keypair        /usr/bin/
dist/usr/bin/econe-describe-keypairs     /usr/bin/

# Fireedge

dist/usr/lib/one/fireedge/*     /usr/lib/one/fireedge/*
dist/usr/bin/fireedge-server    /usr/bin/
