.TH OCCI-SERVER "1" "August 2010" "occi-server" "User Commands"
.SH NAME
occi-server \- OpenNebula OCCI service
.SH SYNOPSIS
occi\-server <COMMAND>
.SH DESCRIPTION
.B occi\-server
start or stop OpenNebula OCCI service
.SH COMMANDS
.PP
start
.IP
start the OCCI service
.PP
stop
.IP
stop the OCCI service
.SH FILES
.I /etc/occi-server.conf
.RS
The OCCI service configuration file.
.RE
.I /var/log/one/occi-server.log
.RS
The OCCI server log file.
.SH COPYRIGHT
OpenNebula is Copyright 2002\-2010, Distributed Systems Architecture Group, Universidad
Complutense de Madrid (dsa\-research.org)
.SH AUTHOR
This manual page was written by Damien Raude-Morvan <drazzib@debian.org>,
for the Debian GNU/Linux system (but may be used by others).