.TH SUNSTONE-SERVER "1" "June 2011" "sunstone-server " "User Commands"
.SH NAME
sunstone-server \- OpenNebula Sunstone web control interface
.SH SYNOPSIS
.B sunstone-server
[\fI-H host\fR] [\fI-p port\fR]
.SH DESCRIPTION
\fB\-H\fR: Host for the Sunstone server, default value: localhost
\fB\-p\fR: Port for incoming connections, default value: 9869
.PP
Usage: sunstone\-server [\-H host] [\-p port]
.PP
\fB\-H\fR: Host for the Sunstone server, default value: localhost
\fB\-p\fR: Port for incoming connections, default value: 9869
.SH COPYRIGHT
OpenNebula is Copyright 2002\-2011, Distributed Systems Architecture Group, Universidad
Complutense de Madrid (dsa\-research.org)
.SH AUTHOR
This manual page was written by Damien Raude-Morvan <drazzib@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
