ARG CENTOS_VERSION=8
FROM centos:${CENTOS_VERSION}

#
# BUILD ARGS
#

ARG IMAGE_VERSION=1.0
ARG OPENNEBULA_LICENSE
ARG CENTOS_VERSION
ARG OPENNEBULA_VERSION="5.12"
ARG OPENNEBULA_URL_REPO="https://downloads.opennebula.io/repo/${OPENNEBULA_VERSION}/CentOS/\$releasever/\$basearch"
ARG OPENNEBULA_URL_GPGKEY="https://downloads.opennebula.io/repo/repo.key"
# TODO: ARG DOCKER_VERSION=19.03

#
# LABELS
#

LABEL version="${IMAGE_VERSION}"
LABEL maintainer="OpenNebula Team (contact@opennebula.io)"
LABEL description="OpenNebula Frontend - Dockerized OpenNebula"
LABEL org.label-schema.name="opennebula-frontend"
LABEL org.label-schema.description="OpenNebula Frontend - Dockerized OpenNebula"
LABEL org.label-schema.version="${IMAGE_VERSION}"
LABEL org.label-schema.license="${OPENNEBULA_LICENSE}"
LABEL org.label-schema.vendor="OpenNebula"
LABEL org.opencontainers.image.title="opennebula-frontend"
LABEL org.opencontainers.image.description="OpenNebula Frontend - Dockerized OpenNebula"
LABEL org.opencontainers.image.version="${IMAGE_VERSION}"
LABEL org.opencontainers.image.authors="OpenNebula Team (contact@opennebula.io)"
LABEL org.opencontainers.image.licenses="${OPENNEBULA_LICENSE}"
LABEL org.opencontainers.image.vendor="OpenNebula"

# image params

LABEL org.label-schema.docker.params="OPENNEBULA_FRONTEND_SERVICE=Fontend service to run (or all), \
OPENNEBULA_FRONTEND_SSH_HOSTNAME=Host to which node will ssh into, \
OPENNEBULA_ONED_HOSTNAME=Host of the oned API server, \
OPENNEBULA_ONED_APIPORT=Port of the oned server, \
OPENNEBULA_ONEFLOW_HOSTNAME=Host of the oneflow server, \
OPENNEBULA_ONEFLOW_APIPORT=Port of the oneflow server, \
OPENNEBULA_ONEGATE_HOSTNAME=Host of the onegate server, \
OPENNEBULA_ONEGATE_APIPORT=Port of the onegate server, \
OPENNEBULA_MEMCACHED_HOSTNAME=Host of the memcached server, \
OPENNEBULA_MEMCACHED_APIPORT=Port of the memcached server, \
OPENNEBULA_SUNSTONE_HTTPD=yes/no if sunstone should use the apache webserver, \
OPENNEBULA_SUNSTONE_MEMCACHED=yes/no if sunstone should use the memcached, \
OPENNEBULA_SUNSTONE_HTTPPORT=HTTP port for the sunstone server, \
OPENNEBULA_SUNSTONE_HTTPSPORT=HTTPS port for the sunstone server, \
OPENNEBULA_SUNSTONE_HTTP_REDIRECT=yes/no if HTTP traffic should be redirected to HTTPS, \
OPENNEBULA_SUNSTONE_HTTPS_ONLY=yes/no if only HTTPS should be used, \
OPENNEBULA_SUNSTONE_HTTPS_ENABLED=yes/no if HTTPS should be enabled at all, \
OPENNEBULA_SUNSTONE_PUBLISHED_HTTPPORT=Published HTTP port on the host part, \
OPENNEBULA_SUNSTONE_PUBLISHED_HTTPSPORT=Published HTTPS port on the host part, \
OPENNEBULA_SUNSTONE_VNCPORT=Port of the VNC server, \
OPENNEBULA_TLS_DOMAIN_LIST=Space separated list of DNS names (asterisk allowed), \
OPENNEBULA_TLS_VALID_DAYS=Expiration days for the generated self-signed certificate, \
OPENNEBULA_TLS_CERT_BASE64=Custom certificate in base64 format, \
OPENNEBULA_TLS_KEY_BASE64=Privkey to the custom certificate in base64 format, \
OPENNEBULA_TLS_CERT=Custom certificate as a filename, \
OPENNEBULA_TLS_KEY=Privkey to the custom certificate as a filename, \
ONEADMIN_PASSWORD=Password for the oneadmin user (otherwise generated), \
ONEADMIN_SSH_PRIVKEY=Privkey of the custom ssh key as a filename, \
ONEADMIN_SSH_PUBKEY=Pubkey of the custom ssh key as a filename, \
MYSQL_HOST=Host of the mysql server, \
MYSQL_PORT=Port of the mysql server, \
MYSQL_DATABASE=Database name for the OpenNebula database, \
MYSQL_USER=Database user for the OpenNebula database, \
MYSQL_PASSWORD=Password of the OpenNebula database user, \
MYSQL_ROOT_PASSWORD=Root password of the mysql server"

#
# PACKAGES
#

# basic packages (and remove kdump)
RUN dnf -y remove kexec-tools && dnf -y update && dnf -y install \
        epel-release \
        yum-utils \
    && dnf clean all && rm -rf /var/cache/dnf/*

# prepare opennebula repo
RUN { \
        echo "[opennebula]" ; \
        echo "name=opennebula" ; \
        echo "enabled=1" ; \
        echo "baseurl=${OPENNEBULA_URL_REPO}" ; \
        if [ -n "${OPENNEBULA_URL_GPGKEY}" ] ; then \
            echo "gpgkey=${OPENNEBULA_URL_GPGKEY}" ; \
            echo "gpgcheck=1" ; \
            echo "repo_gpgcheck=1" ; \
        fi \
    } >> /etc/yum.repos.d/opennebula.repo
RUN chown root:root /etc/yum.repos.d/opennebula.repo
RUN chmod 0644 /etc/yum.repos.d/opennebula.repo
RUN sed -i "s/[\$][{]OPENNEBULA_VERSION[}]/${OPENNEBULA_VERSION}/" \
        /etc/yum.repos.d/opennebula.repo

# prepare docker repo
RUN yum-config-manager --add-repo \
        https://download.docker.com/linux/centos/docker-ce.repo

# prepare phusion passenger repo
RUN curl --fail -sSLo /etc/yum.repos.d/passenger.repo \
        https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo

# opennebula packages and dependencies
RUN dnf -y install \
        crontabs \
        logrotate \
        supervisor \
        mariadb \
        mariadb-server \
        expect \
        docker-ce-cli \
        memcached \
        httpd \
        mod_ssl \
        passenger \
        mod_passenger \
        opennebula-server \
        opennebula-ruby \
        opennebula-flow \
        opennebula-gate \
        opennebula-sunstone \
        file \
        e2fsprogs \
        nc \
    && dnf clean all && rm -rf /var/cache/dnf/*

#
# CONFIGURATION
#

# each container should have unique machine-id (autogenerated on start)
RUN rm -f /etc/machine-id

# cleanup supervisord's config files
RUN rm -rf /etc/supervisord.* && mkdir -p /etc/supervisord.d

# create supervisord logdir
RUN mkdir -p /var/log/supervisor/services

# TODO: remove this when supervisord becomes part of one repo
# copy supervised service files
COPY supervisord /usr/share/one/supervisord
RUN chown -R root:root /usr/share/one/supervisord
RUN chmod 0755 /usr/share/one/supervisord
RUN chmod 0755 /usr/share/one/supervisord/service
RUN chmod 0755 /usr/share/one/supervisord/supervisord.d
RUN chmod 0644 /usr/share/one/supervisord/supervisord.conf
RUN chmod 0600 /usr/share/one/supervisord/supervisord.d/*.ini
RUN chmod 0755 /usr/share/one/supervisord/service/*.sh

# cleanup the oneadmin's ssh
RUN for f in authorized_keys id_rsa id_rsa.pub ; do rm -f "/var/lib/one/.ssh/${f}" ; done

# configure sshd
RUN sed -i \
        -e '/PermitRootLogin/d' \
        -e '/PasswordAuthentication/d' \
        -e '/PermitEmptyPasswords/d' \
        -e '/PubkeyAuthentication/d' \
        /etc/ssh/sshd_config \
    && { \
        echo 'PermitRootLogin no' ; \
        echo 'PasswordAuthentication no' ; \
        echo 'PermitEmptyPasswords no' ; \
        echo 'PubkeyAuthentication yes' ; \
    } >> /etc/ssh/sshd_config

# cleanup the ssh host keys if present
RUN rm -f /etc/ssh/ssh_host_*

# create oneadmin's "root" directory for its volumes
RUN mkdir -p /oneadmin \
    && chown root:root /oneadmin \
    && chmod 0755 /oneadmin

# apache config
COPY conf/httpd.conf /etc/httpd/conf/httpd.conf
RUN chown root:root /etc/httpd/conf/httpd.conf
RUN chmod 644 /etc/httpd/conf/httpd.conf
COPY conf/opennebula-httpd.conf /etc/httpd/conf.d/opennebula.conf
RUN chown root:root /etc/httpd/conf.d/opennebula.conf
RUN chmod 644 /etc/httpd/conf.d/opennebula.conf
RUN rm -f /etc/httpd/conf.d/welcome.conf
RUN rm -f /etc/httpd/conf.d/ssl.conf

# memcached config
COPY conf/memcached.conf /etc/sysconfig/memcached
RUN chown root:root /etc/sysconfig/memcached
RUN chmod 644 /etc/sysconfig/memcached

# passenger config
# TODO: is this needed?
RUN ln -s /usr/share/ruby/vendor_ruby/phusion_passenger \
        /usr/share/passenger/phusion_passenger

# permission settings according to:
# https://docs.opennebula.io/stable/deployment/sunstone_setup/suns_advance.html
RUN chmod a+x /var/lib/one
RUN chmod a+x /var/lib/one/sunstone

#
# CLEANUP
#

# NOTE:
# This has meaning only when the built image is squashed or obfuscated (as we
# do here via the two-stage build) - otherwise it will just hide these deleted
# files in the top layer but they are still easily retrievable!

RUN rm -rf \
        /etc/yum.repos.d/opennebula.repo \
        /var/log/dnf* \
        /var/log/anaconda \
        /var/log/hawkey.log
RUN find \
        /tmp \
        /var/tmp \
        -mindepth 1 -maxdepth 1 -exec rm -rf '{}' \;
RUN truncate -c -s 0 \
        /var/log/wtmp \
        /var/log/btmp \
        /var/log/lastlog

#
# HEALTHCHECK
#

COPY onedocker-healthcheck.sh /
RUN chown root:root /onedocker-healthcheck.sh
RUN chmod 0755 /onedocker-healthcheck.sh

# this is a docker extension and it is not part of OCI definition - logic is
# moved to the docker-compose file now
#HEALTHCHECK --start-period=2m --interval=10s --retries=3 --timeout=10s \
#    CMD [ "/onedocker-healthcheck.sh" ]

#
# ENTRYPOINT
#

# onedocker script which is doing the heavy-lifting
COPY onedocker-frontend.sh /
RUN chown root:root /onedocker-frontend.sh
RUN chmod 0755 /onedocker-frontend.sh

ENTRYPOINT [ "/onedocker-frontend.sh" ]

# our entrypoint does not parse arguments
#CMD [ "NO-EFFECT" ]

#
# PUBLISHED SERVICES
#

# these are the default ports - *most* of them can be changed on every start...
# the exceptions are sshd and mysqld services for the moment

# sshd:
EXPOSE 22/tcp

# mysql:
EXPOSE 3306/tcp

# sunstone:
EXPOSE 9869/tcp
EXPOSE 80/tcp
EXPOSE 443/tcp

# oned:
EXPOSE 2633/tcp

# oneflow:
EXPOSE 2474/tcp

# onegate:
EXPOSE 5030/tcp

# memcached:
EXPOSE 11211/tcp

# vnc:
EXPOSE 29876/tcp

